# Cognito Pre-Signup trigger — rejects disposable/temporary email domains.
# Invoked by Cognito automatically before a new user is created.

BLOCKED_DOMAINS = {
    # ── High-volume throwaway services ────────────────────────────────────────
    "mailinator.com", "guerrillamail.com", "guerrillamail.net", "guerrillamail.org",
    "guerrillamail.de", "guerrillamail.biz", "guerrillamail.info",
    "tempmail.com", "temp-mail.org", "temp-mail.io", "tempmail.net",
    "throwam.com", "throwaway.email", "trashmail.com", "trashmail.net",
    "trashmail.at", "trashmail.io", "trashmail.me",
    "sharklasers.com", "guerrillamailblock.com", "grr.la", "guerrillamail.info",
    "spam4.me", "yopmail.com", "yopmail.fr", "cool.fr.nf", "jetable.fr.nf",
    "nospam.ze.tc", "nomail.xl.cx", "mega.zik.dj", "speed.1s.fr",
    "courriel.fr.nf", "moncourrier.fr.nf", "monemail.fr.nf", "monmail.fr.nf",
    "maildrop.cc", "mailnull.com", "spamgourmet.com", "spamgourmet.net",
    "spamgourmet.org", "spamspot.com", "spamevader.com",
    "dispostable.com", "discardmail.com", "discardmail.de", "spamwc.de",
    "spamwc.net", "spamwc.org",
    "fakeinbox.com", "fakeinbox.net", "fakeinbox.org", "tempinbox.com",
    "tempinbox.net", "throwam.com",
    "mailnesia.com", "mailnull.com", "spamfree24.org", "spamfree24.de",
    "spamfree24.net", "spamfree24.com",
    "spamgob.com", "mt2009.com", "mt2014.com", "mt2015.com",
    "discard.email", "spam.la", "bigstring.com",
    "getairmail.com", "filzmail.de", "throwam.com",
    "spamherelots.com", "spamhereplease.com", "spam.to",
    "binkmail.com", "bio-muesli.net", "bobmail.info",
    "crap.2ya.com", "devnullmail.com",
    "e4ward.com", "email60.com", "emailias.com",
    "emailinfive.com", "emailtemporanea.net",
    "emailwarden.com", "ezehe.com",
    "frapmail.com", "gishpuppy.com",
    "haltospam.com", "ieatspam.eu", "ieatspam.info",
    "imails.info", "inbax.tk", "inoutmail.de",
    "jetable.com", "jetable.net", "jetable.org",
    "jnxjn.com", "kasmail.com", "klassmaster.com",
    "klzlk.com", "kurzepost.de",
    "lol.ovpn.to", "lookugly.com", "lortemail.dk",
    "m21.cc", "mail.by", "mail1a.de", "mail2rss.org",
    "mail333.com", "mailbidon.com", "mailblocks.com",
    "mailbolt.com", "mailc.net", "mailchop.com",
    "maildu.de", "maileater.com", "mailexpire.com",
    "mailf5.com", "mailfall.com", "mailforspam.com",
    "mailfreeonline.com", "mailguard.me", "mailimate.com",
    "mailme.lv", "mailme24.com", "mailmetrash.com",
    "mailmoat.com", "mailnew.com", "mailpick.biz",
    "mailrock.biz", "mailsac.com", "mailscrap.com",
    "mailshell.com", "mailsiphon.com", "mailslapping.com",
    "mailslite.com", "mailsru.com", "mailtemp.net",
    "mailtome.de", "mailtothis.com", "mailtrash.net",
    "mailu.gq", "mailzilla.com", "mailzilla.org",
    "mbx.cc", "mega.zik.dj", "meltmail.com",
    "messagebeamer.de", "mierdamail.com",
    "mintemail.com", "moburl.com", "moncourrier.fr.nf",
    "monemail.fr.nf", "monmail.fr.nf", "msa.minsmail.com",
    "mt2009.com", "mymail-in.net", "mymailoasis.com",
    "mytempemail.com", "mytrashmail.com", "neomailbox.com",
    "neptune.de", "netmails.net", "netmails.com",
    "netzidiot.de", "nevermail.de", "nobulk.com",
    "noclickemail.com", "nogmailspam.info", "nospamfor.us",
    "nospammail.net", "notmailinator.com", "nowmymail.com",
    "nus.edu.sg", "objectmail.com", "odaymail.com",
    "oe88.com", "okrent.us", "oneoffemail.com",
    "onewaymail.com", "online.ms", "oopi.org",
    "opentrash.com", "ordinaryamerican.net", "otherinbox.com",
    "owlpic.com", "pancakemail.com", "pcusers.de",
    "pjjkp.com", "plexolan.de", "pookmail.com",
    "powered.name", "proxymail.eu", "prtnx.com",
    "punkass.com", "putthisinyourspamdatabase.com",
    "qq.com", "quickinbox.com",
    "rcpt.at", "rklips.com", "rmqkr.net",
    "rppkn.com", "rtrtr.com",
    "s0ny.net", "safe-mail.net", "safersignup.de",
    "safetymail.info", "safetypost.de", "sandelf.de",
    "sbi.hu", "SendSpamHere.com", "sharklasers.com",
    "shieldedmail.com", "shitmail.me", "shitware.nl",
    "shortmail.net", "sibmail.com", "sneakemail.com",
    "snkmail.com", "sofort-mail.de", "sogetthis.com",
    "soodonims.com", "spam.la", "spamail.de",
    "spamdecoy.net", "spamfree.eu", "spamgob.com",
    "spamgoes.in", "spamherelots.com", "spamhereplease.com",
    "spamhole.com", "spamify.com", "spaminmotion.com",
    "spamkill.info", "spaml.com", "spaml.de",
    "spammotel.com", "spammy.host", "spamok.com",
    "spamomatic.net", "spamota.com", "spamslicer.com",
    "spamspot.com", "spamsub.com", "spamthis.co.uk",
    "spamthisplease.com", "spamtrail.com", "spamtrap.ro",
    "speed.1s.fr", "spoofmail.de", "stuffmail.de",
    "super-auswahl.de", "supergreatmail.com", "supermailer.jp",
    "suremail.info", "sweetxxx.de",
    "tafmail.com", "teewars.org", "teleworm.com",
    "teleworm.us", "temp-mail.ru", "tempail.com",
    "tempalias.com", "tempe-mail.com", "tempemail.biz",
    "tempemail.co.za", "tempemail.com", "tempemail.net",
    "tempinbox.co.uk", "tempmail.eu", "tempmail.it",
    "tempomail.fr", "temporarioemail.com.br",
    "temporaryemail.net", "temporaryemail.us",
    "temporaryforwarding.com", "temporaryinbox.com",
    "temporarymailaddress.com", "thankyou2010.com",
    "thecloudindex.com", "thinst.com", "throwam.com",
    "throwam.net", "throwaway.email",
    "tilien.com", "tittbit.in", "tmail.com",
    "tmailinator.com", "toiea.com", "tradermail.info",
    "trash-amil.com", "trash-mail.at", "trash-mail.com",
    "trash-mail.de", "trash-mail.ga", "trash-mail.io",
    "trash-mail.ml", "trash-me.com", "trash2009.com",
    "trashdevil.com", "trashdevil.de", "trashemail.de",
    "trashimail.de", "trashinbox.com", "trashmail.at",
    "trashmail.com", "trashmail.de", "trashmail.io",
    "trashmail.me", "trashmail.net", "trashmail.org",
    "trashmail2.com", "trashmailer.com", "trashmailt.com",
    "trashware.de", "trashymail.com", "trbvm.com",
    "trillianpro.com", "turual.com", "twinmail.de",
    "tyldd.com", "uggsrock.com",
    "umail.net", "upliftnow.com",
    "uroid.com", "us.af",
    "venompen.com", "veryrealemail.com", "viditag.com",
    "viralplays.com", "vmail.me",
    "wazabi.club", "webemail.me", "weg-werf-email.de",
    "wegwerf-email.at", "wegwerfadresse.de", "wegwerfemail.com",
    "wegwerfemail.de", "wegwerfemail.net", "wegwerfemail.org",
    "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
    "wetrainbayarea.com", "whyspam.me", "willhackforfood.biz",
    "willselfdestruct.com", "winemaven.info", "wronghead.com",
    "www.e4ward.com", "wuzupmail.net",
    "xagloo.com", "xemaps.com", "xents.com",
    "xmaily.com", "xoxox.cc", "xyzmail.com",
    "yahomail.in", "yam.eu", "yanet.me",
    "yeah.net", "yep.it", "yogamaven.com",
    "yopmail.com", "ypmail.webarnak.fr.eu.org",
    "yuurok.com", "z1p.biz", "za.com",
    "zehnminuten.de", "zehnminutenmail.de",
    "zetmail.com", "zippymail.info",
    "zoemail.com", "zoemail.net", "zoemail.org",
    "zomg.info",
}


def lambda_handler(event: dict, _context: object) -> dict:
    """
    Cognito Pre-Signup trigger.
    Returns the event unchanged to allow signup, or raises Exception to block it.
    """
    email: str = event.get("request", {}).get("userAttributes", {}).get("email", "")
    domain = email.lower().split("@")[-1] if "@" in email else ""

    if domain in BLOCKED_DOMAINS:
        raise Exception(
            "Email temporário ou descartável não é permitido. "
            "Por favor, use seu email pessoal ou profissional."
        )

    return event
